# Generated by Django 5.1.7 on 2025-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='keyword_matches',
            field=models.TextField(blank=True),
        ),
    ]
